let strip: neopixel.Strip = null
basic.forever(function () {
    maqueen.writeLED(maqueen.LED.LEDLeft, maqueen.LEDswitch.turnOn)
    maqueen.writeLED(maqueen.LED.LEDRight, maqueen.LEDswitch.turnOn)
    music.playMelody("C5 B A G F E D C ", 120)
    strip = neopixel.create(DigitalPin.P15, 4, NeoPixelMode.RGB)
    strip.setBrightness(10)
    strip.showRainbow(1, 120)
    strip.show()
    maqueen.motorRun(maqueen.Motors.All, maqueen.Dir.CW, 100)
    maqueen.motorRun(maqueen.Motors.All, maqueen.Dir.CCW, 100)
    maqueen.motorStop(maqueen.Motors.All)
    maqueen.motorRun(maqueen.Motors.M1, maqueen.Dir.CW, 80)
    maqueen.motorRun(maqueen.Motors.M2, maqueen.Dir.CCW, 80)
    maqueen.motorStop(maqueen.Motors.All)
    maqueen.motorRun(maqueen.Motors.M2, maqueen.Dir.CW, 100)
    maqueen.motorRun(maqueen.Motors.M1, maqueen.Dir.CW, 100)
    maqueen.motorRun(maqueen.Motors.M2, maqueen.Dir.CW, 60)
    maqueen.motorRun(maqueen.Motors.M1, maqueen.Dir.CCW, 60)
    maqueen.motorStop(maqueen.Motors.All)
})
basic.forever(function () {
    strip.show()
    basic.pause(100)
    strip.rotate(1)
})
